In [31]:
import numpy as np
import pandas as pd

from keras.models import Sequential
from keras.layers.core import Dense, Dropout, Activation
from keras.optimizers import Adam
import matplotlib.pyplot as plt
from sklearn.metrics import roc_curve, auc
from sklearn.model_selection import train_test_split

def wordCharacterToUnicode(arr, arrOutput):
  for i in range(0, len(arr)):
    temp = arr[i];
    count = 0
    for j in temp:
      arrOutput[i][count]= ord(j)
      count = count + 1

def labelToDataframe(arry, arryoutput):
  for i in range (0, len(arry)):
    for j in range (0, len(arry[i])):
      temp = arry[i][j]
      if (temp!= None):
        arryoutput.loc[i][temp] = 1

data = pd.read_csv('inputbn.csv', sep=',', engine='python', header=0)
data = data.to_numpy()

x_sample = data[:,0]
y_sample = data[:,1:10]
temp = np.zeros(shape = (100, 46))

X = np.zeros(shape = (100, 10))
wordCharacterToUnicode(x_sample, X)
temp = np.zeros(shape = (100, 46))
df = pd.DataFrame(temp, columns=['অ','আ','ই','ঈ','উ','ঊ','ঋ','এ','ঐ','ও','ঔ','ক','খ','গ','ঘ','ঙ','চ','ছ','জ','ঝ','ঞ','ট','ঠ','ড','ঢ','ণ','ত','থ','দ','ধ','ন','প','ফ','ব','ভ','ম','য','র','ল','শ','ষ','স','হ','ড়','ঢ়','য়'])
labelToDataframe(y_sample, df)
print(X[0:15])
df.head()

trainX, testX, trainy, testy = train_test_split(X, df, test_size=0.1)

[[2476. 2482. 2494.    0.    0.    0.    0.    0.    0.    0.]
 [2453. 2469. 2494.    0.    0.    0.    0.    0.    0.    0.]
 [2439. 2482. 2495. 2486.    0.    0.    0.    0.    0.    0.]
 [2476. 2494. 2482. 2495. 2453. 2494.    0.    0.    0.    0.]
 [2478. 2472. 2503.    0.    0.    0.    0.    0.    0.    0.]
 [2488. 2494. 2474.    0.    0.    0.    0.    0.    0.    0.]
 [2458. 2495. 2464. 2495.    0.    0.    0.    0.    0.    0.]
 [2489. 2494. 2482. 2453. 2494.    0.    0.    0.    0.    0.]
 [2474. 2494. 2454. 2494. 2482. 2495.    0.    0.    0.    0.]
 [2453. 2494. 2480. 2476. 2494. 2480. 2495.    0.    0.    0.]
 [2482. 2495. 2454. 2468. 2503.    0.    0.    0.    0.    0.]
 [2482. 2503. 2454. 2494. 2474. 2524. 2494.    0.    0.    0.]
 [2482. 2472. 2509. 2465. 2472.    0.    0.    0.    0.    0.]
 [2488. 2480. 2453. 2494. 2480.    0.    0.    0.    0.    0.]
 [2489. 2494. 2482. 2497. 2478.    0.    0.    0.    0.    0.]]


In [0]:

#define model
model = Sequential()
model.add(Dense(100, input_shape=(10,), activation='relu'))
model.add(Dense(75, activation='relu'))
model.add(Dense(46, activation='relu'))
model.add(Activation('softmax'))

# compile model
opt = Adam(lr=0.01)
model.compile(loss='mse', optimizer=opt, metrics=['accuracy'])

#fit model (train)
history = model.fit(trainX, trainy, validation_data=(testX, testy), batch_size=5, epochs=10000, verbose=0)

In [42]:
# evaluate the keras model
loss, accuracy = model.evaluate(X, df)
print("\nLoss: %.3f, Accuracy: %.2f%%" % (loss, accuracy*100))

tempString = 'সরকারি'
Y = [0,1,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,1,0,0,0,0]
print(len(Y))
tempInput = np.zeros(shape = (1,10))
wordCharacterToUnicode(tempString, tempInput)
probabilities = model.predict(tempInput)
predictions = [float(round(x)) for x in probabilities]
accuracy = numpy.mean(predictions == Y)
print("Prediction Accuracy: %.2f%%" % (accuracy*100))


100/100 [==============================] - 0s 85us/step

Loss: 0.106, Accuracy: 10.00%
46


IndexError: ignored